wireplumber.settings = {
    device.routes = {
        alsa_output.usb-3142_fifine_Headset-00.pro-output-0 = {
            target = "fifine"
        }
    }
}

monitor.alsa.rules = [
    {
        matches = [
            {
                node.name = "alsa_output.usb-3142_fifine_Headset-00.pro-output-0"
            }
        ]
        actions = {
            update-props = {
                node.priority = 10000
                node.preferred = true
            }
        }
    }
]